// This file was generated by counterfeiter
package usecasesfakes

import (
	"sync"

	"github.com/tjarratt/doit-etre-rad/backend/usecases"
)

type FakeAddPhraseUseCase struct {
	ExecuteStub        func(usecases.AddPhraseRequest) ([]usecases.PhraseResponse, error)
	executeMutex       sync.RWMutex
	executeArgsForCall []struct {
		arg1 usecases.AddPhraseRequest
	}
	executeReturns struct {
		result1 []usecases.PhraseResponse
		result2 error
	}
	executeReturnsOnCall map[int]struct {
		result1 []usecases.PhraseResponse
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAddPhraseUseCase) Execute(arg1 usecases.AddPhraseRequest) ([]usecases.PhraseResponse, error) {
	fake.executeMutex.Lock()
	ret, specificReturn := fake.executeReturnsOnCall[len(fake.executeArgsForCall)]
	fake.executeArgsForCall = append(fake.executeArgsForCall, struct {
		arg1 usecases.AddPhraseRequest
	}{arg1})
	fake.recordInvocation("Execute", []interface{}{arg1})
	fake.executeMutex.Unlock()
	if fake.ExecuteStub != nil {
		return fake.ExecuteStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.executeReturns.result1, fake.executeReturns.result2
}

func (fake *FakeAddPhraseUseCase) ExecuteCallCount() int {
	fake.executeMutex.RLock()
	defer fake.executeMutex.RUnlock()
	return len(fake.executeArgsForCall)
}

func (fake *FakeAddPhraseUseCase) ExecuteArgsForCall(i int) usecases.AddPhraseRequest {
	fake.executeMutex.RLock()
	defer fake.executeMutex.RUnlock()
	return fake.executeArgsForCall[i].arg1
}

func (fake *FakeAddPhraseUseCase) ExecuteReturns(result1 []usecases.PhraseResponse, result2 error) {
	fake.ExecuteStub = nil
	fake.executeReturns = struct {
		result1 []usecases.PhraseResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeAddPhraseUseCase) ExecuteReturnsOnCall(i int, result1 []usecases.PhraseResponse, result2 error) {
	fake.ExecuteStub = nil
	if fake.executeReturnsOnCall == nil {
		fake.executeReturnsOnCall = make(map[int]struct {
			result1 []usecases.PhraseResponse
			result2 error
		})
	}
	fake.executeReturnsOnCall[i] = struct {
		result1 []usecases.PhraseResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeAddPhraseUseCase) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.executeMutex.RLock()
	defer fake.executeMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeAddPhraseUseCase) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ usecases.AddPhraseUseCase = new(FakeAddPhraseUseCase)
