// This file was generated by counterfeiter
package httpserverfakes

import (
	"net/http"
	"sync"

	"github.com/tjarratt/doit-etre-rad/backend/httpserver"
)

type FakeShowPhrasesParamReader struct {
	ReadParamsFromRequestStub        func(*http.Request) (httpserver.ShowPhrasesParams, error)
	readParamsFromRequestMutex       sync.RWMutex
	readParamsFromRequestArgsForCall []struct {
		arg1 *http.Request
	}
	readParamsFromRequestReturns struct {
		result1 httpserver.ShowPhrasesParams
		result2 error
	}
	readParamsFromRequestReturnsOnCall map[int]struct {
		result1 httpserver.ShowPhrasesParams
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeShowPhrasesParamReader) ReadParamsFromRequest(arg1 *http.Request) (httpserver.ShowPhrasesParams, error) {
	fake.readParamsFromRequestMutex.Lock()
	ret, specificReturn := fake.readParamsFromRequestReturnsOnCall[len(fake.readParamsFromRequestArgsForCall)]
	fake.readParamsFromRequestArgsForCall = append(fake.readParamsFromRequestArgsForCall, struct {
		arg1 *http.Request
	}{arg1})
	fake.recordInvocation("ReadParamsFromRequest", []interface{}{arg1})
	fake.readParamsFromRequestMutex.Unlock()
	if fake.ReadParamsFromRequestStub != nil {
		return fake.ReadParamsFromRequestStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.readParamsFromRequestReturns.result1, fake.readParamsFromRequestReturns.result2
}

func (fake *FakeShowPhrasesParamReader) ReadParamsFromRequestCallCount() int {
	fake.readParamsFromRequestMutex.RLock()
	defer fake.readParamsFromRequestMutex.RUnlock()
	return len(fake.readParamsFromRequestArgsForCall)
}

func (fake *FakeShowPhrasesParamReader) ReadParamsFromRequestArgsForCall(i int) *http.Request {
	fake.readParamsFromRequestMutex.RLock()
	defer fake.readParamsFromRequestMutex.RUnlock()
	return fake.readParamsFromRequestArgsForCall[i].arg1
}

func (fake *FakeShowPhrasesParamReader) ReadParamsFromRequestReturns(result1 httpserver.ShowPhrasesParams, result2 error) {
	fake.ReadParamsFromRequestStub = nil
	fake.readParamsFromRequestReturns = struct {
		result1 httpserver.ShowPhrasesParams
		result2 error
	}{result1, result2}
}

func (fake *FakeShowPhrasesParamReader) ReadParamsFromRequestReturnsOnCall(i int, result1 httpserver.ShowPhrasesParams, result2 error) {
	fake.ReadParamsFromRequestStub = nil
	if fake.readParamsFromRequestReturnsOnCall == nil {
		fake.readParamsFromRequestReturnsOnCall = make(map[int]struct {
			result1 httpserver.ShowPhrasesParams
			result2 error
		})
	}
	fake.readParamsFromRequestReturnsOnCall[i] = struct {
		result1 httpserver.ShowPhrasesParams
		result2 error
	}{result1, result2}
}

func (fake *FakeShowPhrasesParamReader) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.readParamsFromRequestMutex.RLock()
	defer fake.readParamsFromRequestMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeShowPhrasesParamReader) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ httpserver.ShowPhrasesParamReader = new(FakeShowPhrasesParamReader)
